/**
 * BAIOS - Editor IA
 * Event Bus Context — Phase 2.003
 * Immutable event envelope for transport. No logic.
 */

import type { EditorEventName } from '../events/event.names';
import type { EditorEventPayloadMap } from '../events/event.payloads';

/** Envelope that travels through the event bus */
export interface EventBusEnvelope {
  /** Unique delivery ID generated by the bus */
  deliveryId: string;
  /** Published event name */
  eventName: EditorEventName;
  /** ISO-8601 publish timestamp */
  publishedAt: string;
  /** Payload associated with the event */
  payload: unknown;
  /** Trace context for propagation */
  traceId: string;
  /** Correlation ID */
  correlationId: string;
  /** Whether the event has been delivered to all subscribers */
  delivered: boolean;
  /** Number of subscribers that received this event */
  subscriberCount: number;
}