/**
 * BAIOS - Editor IA
 * Error Codes — Phase 1D (CORE FROZEN)
 */

export const ERROR_CODES = {
  VALIDATION: {
    FIELD_REQUIRED: 'ERR_VAL_001',
    INVALID_FORMAT: 'ERR_VAL_002',
    OUT_OF_RANGE: 'ERR_VAL_003',
  },
  WORKFLOW: {
    INVALID_TRANSITION: 'ERR_WF_001',
    DEPENDENCY_FAILED: 'ERR_WF_002',
    TIMEOUT: 'ERR_WF_003',
  },
  PIPELINE: {
    STAGE_FAILED: 'ERR_PIPE_001',
    OUTPUT_INVALID: 'ERR_PIPE_002',
  },
  PROVIDER: {
    UNAVAILABLE: 'ERR_PROV_001',
    RATE_LIMITED: 'ERR_PROV_002',
    INVALID_RESPONSE: 'ERR_PROV_003',
  },
  SCHEDULER: {
    WINDOW_CLOSED: 'ERR_SCH_001',
    CONFLICT: 'ERR_SCH_002',
  },
  POLICY: {
    BLOCKER: 'ERR_POL_001',
    WARNING: 'ERR_POL_002',
  },
  PUBLICATION: {
    CHANNEL_UNAVAILABLE: 'ERR_PUB_001',
    ALREADY_PUBLISHED: 'ERR_PUB_002',
  },
  UNKNOWN: {
    INTERNAL: 'ERR_UNK_001',
  },
} as const;