-- Update blog_posts.image_url with specific article images
-- Generated by scripts/update-blog-images.cjs

UPDATE public.blog_posts SET image_url = '/images/articles-webp/Disbiosis.webp' WHERE slug = 'disbiosis-intestinal';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/factores-modulares.webp' WHERE slug = 'permeabilidad-intestinal-leaky-gut';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/sindrome-intestino-irritable.webp' WHERE slug = 'sindrome-del-intestino-irritable-sii';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/sibo.webp' WHERE slug = 'sibo-sobrecrecimiento-bacteriano';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/eje-intestino-cerebro.webp' WHERE slug = 'eje-intestino-cerebro';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/higado-graso-hgna.webp' WHERE slug = 'higado-graso-no-alcoholico-hgna';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/reflujo-gastroesofagico-erge.webp' WHERE slug = 'reflujo-gastroesofagico-erge';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/celiaquia-vs-sensibilidad-gluten.webp' WHERE slug = 'celiaquia-vs-sensibilidad-al-gluten-no-celiaca';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/digestion-enzimatica-exocrina.webp' WHERE slug = 'digestion-enzimatica-exocrina';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/fibra-soluble-vs-insoluble.webp' WHERE slug = 'fibra-soluble-vs-insoluble-en-la-motilidad';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/acidos-grasos-cadena-corta-butirato.webp' WHERE slug = 'acidos-grasos-de-cadena-corta-butirato';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/estrenimiento-cronico.webp' WHERE slug = 'estrenimiento-funcional-cronico';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/metabolismo-acidos-biliares.webp' WHERE slug = 'metabolismo-de-los-acidos-biliares';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/helicobacter-pylori.webp' WHERE slug = 'infeccion-por-helicobacter-pylori';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/eje-intestino-higado.webp' WHERE slug = 'eje-intestino-higado';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/intolerancia-a-la-lactosa.webp' WHERE slug = 'intolerancia-a-la-lactosa-genetica-vs-adquirida';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/alergias-alimentarias-ige.webp' WHERE slug = 'alergias-alimentarias-y-respuesta-ige';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/histaminosis-enterica.webp' WHERE slug = 'histaminosis-enterica';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/funcion-moco-gastrico.webp' WHERE slug = 'funcion-del-moco-gastrico';
UPDATE public.blog_posts SET image_url = '/images/articles-webp/transito-intestinal-acelerado-principal.webp' WHERE slug = 'transito-intestinal-acelerado';
