-- Tabla para almacenar eventos de chat y alertas comerciales
CREATE TABLE IF NOT EXISTS chat_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  session_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  product_name TEXT,
  score INTEGER NOT NULL DEFAULT 0,
  cache_hit BOOLEAN DEFAULT FALSE,
  duration_minutes INTEGER DEFAULT 0,
  question_count INTEGER DEFAULT 0,
  advisor_declined BOOLEAN DEFAULT FALSE,
  metadata JSONB,
  telegram_sent BOOLEAN DEFAULT FALSE,
  telegram_error TEXT
);

CREATE INDEX IF NOT EXISTS idx_chat_events_session_id ON chat_events(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_events_event_type ON chat_events(event_type);
CREATE INDEX IF NOT EXISTS idx_chat_events_created_at ON chat_events(created_at);
CREATE INDEX IF NOT EXISTS idx_chat_events_product_name ON chat_events(product_name);
