-- =============================================
-- HUB PAGES: Autoridad Temática
-- Bienestar en Claro v3
-- =============================================

CREATE TABLE IF NOT EXISTS hub_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category_slug TEXT NOT NULL,
  parent_hub_id UUID REFERENCES hub_pages(id),
  target_keyword TEXT NOT NULL,
  secondary_keywords TEXT[],
  related_entities UUID[],
  related_products UUID[],
  article_count INTEGER DEFAULT 0,
  pillar_content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hub_category ON hub_pages(category_slug);
CREATE INDEX IF NOT EXISTS idx_hub_parent ON hub_pages(parent_hub_id);

-- Hub pages de autoridad
INSERT INTO hub_pages (slug, title, description, category_slug, target_keyword, secondary_keywords, article_count) VALUES
  ('microbiota-intestinal', 'Microbiota Intestinal: Guía Completa',
   'Todo lo que necesitas saber sobre la microbiota intestinal: qué es, cómo cuidarla, disbiosis, probióticos y cómo afecta tu salud global.',
   'microbiota-intestinal', 'microbiota intestinal',
   ARRAY['flora intestinal', 'microbioma', 'probióticos', 'disbiosis', 'bacterias buenas', 'intestino'],
   15),
  ('higado-graso', 'Hígado Graso: Causas, Síntomas y Tratamiento',
   'Guía completa sobre hígado graso no alcohólico: causas, factores de riesgo, síntomas, diagnóstico, tratamiento y prevención.',
   'higado-y-sistema-biliar', 'hígado graso no alcohólico',
   ARRAY['hígado graso', 'NAFLD', 'esteatosis', 'hígado graso en jóvenes', 'hígado graso tratamiento'],
   10),
  ('cirrosis-hepatica', 'Cirrosis Hepática: Todo lo que Necesitas Saber',
   'Información completa sobre cirrosis hepática: causas, síntomas, etapas, diagnóstico, tratamiento y complicaciones.',
   'higado-y-sistema-biliar', 'cirrosis hepática',
   ARRAY['cirrosis', 'hígado cirrótico', 'fibrosis hepática', 'cirrosis causas'],
   8),
  ('estrenimiento-cronico', 'Estreñimiento Crónico: Tratamientos y Remedios',
   'Guía completa sobre el estreñimiento crónico: causas, tratamientos, remedios naturales, cuándo consultar al médico.',
   'tracto-digestivo-inferior', 'estreñimiento crónico',
   ARRAY['estreñimiento', 'constipación', 'tránsito intestinal', 'estrenimiento crónico tratamiento'],
   12),
  ('sindrome-intestino-irritable', 'Síndrome del Intestino Irritable: Guía Completa',
   'Todo sobre el SII: síntomas, causas, diagnóstico, tratamiento, dieta y manejo del síndrome del intestino irritable.',
   'tracto-digestivo-inferior', 'síndrome del intestino irritable',
   ARRAY['SII', 'colon irritable', 'colon espástico', 'SII tratamiento'],
   10),
  ('obesidad', 'Obesidad: Causas, Tratamientos y Prevención',
   'Guía completa sobre obesidad: causas, factores de riesgo, tratamientos médicos y naturales, prevención.',
   'control-de-peso', 'obesidad',
   ARRAY['obesidad causas', 'obesidad tratamiento', 'obesidad prevención', 'sobrepeso'],
   15),
  ('insomnio', 'Insomnio: Causas, Síntomas y Tratamientos',
   'Todo sobre el insomnio: causas, tipos, síntomas, tratamientos, higiene del sueño y cuándo consultar al médico.',
   'sueno-y-descanso', 'insomnio',
   ARRAY['insomnio causas', 'insomnio tratamiento', 'insomnio crónico', 'higiene del sueño'],
   12),
  ('estres-ansiedad', 'Estrés y Ansiedad: Manejo y Tratamiento',
   'Guía completa sobre estrés y ansiedad: causas, síntomas, tratamientos, técnicas de manejo y prevención.',
   'estres-y-ansiedad', 'estrés y ansiedad',
   ARRAY['estrés', 'ansiedad', 'estrés crónico', 'ansiedad generalizada', 'manejo del estrés'],
   14),
  ('presion-arterial-alta', 'Presión Arterial Alta: Todo lo que Necesitas Saber',
   'Información completa sobre hipertensión arterial: causas, síntomas, diagnóstico, tratamiento y prevención.',
   'presion-arterial', 'presión arterial alta',
   ARRAY['hipertensión', 'presión alta', 'tensión alta', 'HTA', 'presion arterial'],
   12),
  ('colesterol-alto', 'Colesterol Alto: Causas, Tratamiento y Prevención',
   'Guía completa sobre colesterol alto: tipos de colesterol, causas, tratamiento, dieta y prevención.',
   'colesterol-y-lipidos', 'colesterol alto',
   ARRAY['colesterol', 'LDL', 'HDL', 'triglicéridos', 'colesterol alto tratamiento'],
   10),
  ('menopausia', 'Menopausia: Síntomas, Tratamientos y Cambios',
   'Todo sobre la menopausia: síntomas, tratamientos hormonales y naturales, cambios físicos y emocionales.',
   'hormonas-sexuales', 'menopausia',
   ARRAY['menopausia síntomas', 'menopausia tratamiento', 'perimenopausia', 'climaterio'],
   10),
  ('reflujo-gastroesofagico', 'Reflujo Gastroesofágico: Causas y Tratamiento',
   'Guía completa sobre reflujo gastroesofágico: ERGE, causas, síntomas, tratamientos y prevención.',
   'tracto-digestivo-superior', 'reflujo gastroesofágico',
   ARRAY['ERGE', 'reflujo ácido', 'reflujo gástrico', 'acidez estomacal'],
   8),
  ('dolor-articular', 'Dolor Articular: Causas, Tratamientos y Prevención',
   'Información completa sobre dolor articular: causas, tipos, tratamientos, prevención y ejercicios.',
   'salud-articular', 'dolor articular',
   ARRAY['dolor de articulaciones', 'artritis', 'artrosis', 'dolor articular tratamiento'],
   8),
  ('depression', 'Depresión Leve: Síntomas, Tratamientos y Prevención',
   'Guía completa sobre depresión leve: síntomas, causas, tratamientos, terapias y prevención.',
   'estado-de-animo', 'depresión leve',
   ARRAY['depresión', 'depresión leve', 'depresión moderada', 'tristeza', 'depresión tratamiento'],
   12),
  ('fatiga-cronica', 'Fatiga Crónica: Causas, Diagnóstico y Tratamiento',
   'Información completa sobre fatiga crónica: causas, síntomas, diagnóstico, tratamiento y prevención.',
   'vitalidad-y-energia', 'fatiga crónica',
   ARRAY['fatiga crónica', 'cansancio crónico', 'fatiga persistente', 'fatiga causas'],
   10),
  ('hinchazon-abdominal', 'Hinchazón Abdominal: Causas y Tratamientos',
   'Guía sobre hinchazón abdominal: causas, cuándo consultar, tratamientos y prevención.',
   'tracto-digestivo-superior', 'hinchazón abdominal',
   ARRAY['hinchazón', 'gases', 'meteorismo', 'hinchazón del vientre', 'inflamación abdominal'],
   8);
